project_id = "dstxrbmetabgbijjeoyf"

[functions.sitemap]
verify_jwt = false

[functions.find-guest-resort]
verify_jwt = false

[functions.generate-insights]
verify_jwt = true

[functions.send-staff-invite]
verify_jwt = true

[functions.create-staff-user]
verify_jwt = true

[functions.send-prearrival-link]
verify_jwt = true

[functions.bootstrap-resort-admin]
verify_jwt = true

[functions.complete-password-reset]
verify_jwt = true
