project_id = "dstxrbmetabgbijjeoyf"

[functions.find-guest-resort]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false

[functions.send-staff-invite]
verify_jwt = true

[functions.create-staff-user]
verify_jwt = false
